name: Build and Deploy the simulator to production environements.

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install Quasar CLI
        run: npm i -g @quasar/cli

      - name: Checkout
        uses: actions/checkout@v4

      - name: ls
        run: ls -la

      - name: Build the app
        run: quasar build

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: ["build"]
